# Generated by Django 5.2 on 2025-04-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Obraz')),
            ],
            options={
                'verbose_name': 'Obraz tła',
                'verbose_name_plural': 'Obrazy tła',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.backgroundimage', verbose_name='Tło')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Trasa',
                'verbose_name_plural': 'Trasy',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Kolejność')),
                ('x', models.PositiveIntegerField(verbose_name='X')),
                ('y', models.PositiveIntegerField(verbose_name='Y')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='editor.route', verbose_name='Trasa')),
            ],
            options={
                'verbose_name': 'Punkt trasy',
                'verbose_name_plural': 'Punkty trasy',
                'ordering': ['order'],
            },
        ),
    ]
